/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const WorkspaceRole = {
  Owner: "Owner",
  Admin: "Admin",
  Member: "Member",
} as const;

export type WorkspaceRole = (typeof WorkspaceRole)[keyof typeof WorkspaceRole];

export const TeamRole = {
  Leader: "Leader",
  Member: "Member",
} as const;

export type TeamRole = (typeof TeamRole)[keyof typeof TeamRole];

export const ProjectRole = {
  Owner: "Owner",
  Product_Owner: "Product_Owner",
  Project_Manager: "Project_Manager",
  Tech_Lead: "Tech_Lead",
  Designer: "Designer",
  Developer: "Developer",
  QC: "QC",
  DevOps: "DevOps",
  Member: "Member",
} as const;

export type ProjectRole = (typeof ProjectRole)[keyof typeof ProjectRole];

export const TaskStatus = {
  Backlog: "Backlog",
  Todo: "Todo",
  In_Progress: "In_Progress",
  Review: "Review",
  Done: "Done",
  Canceled: "Canceled",
} as const;

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export const TaskPriority = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Urgent: "Urgent",
} as const;

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

export const DocumentStatus = {
  Draft: "Draft",
  Published: "Published",
  Archived: "Archived",
} as const;

export type DocumentStatus =
  (typeof DocumentStatus)[keyof typeof DocumentStatus];

export const ProjectStatus = {
  Planning: "Planning",
  Active: "Active",
  On_Hold: "On_Hold",
  Completed: "Completed",
  Archived: "Archived",
} as const;

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus];

export const TaskActivity = {
  TASK_CREATED: "TASK_CREATED",
  TASK_ARCHIVED: "TASK_ARCHIVED",
  TASK_RESTORED: "TASK_RESTORED",
  TASK_DELETED: "TASK_DELETED",
  TITLE_CHANGED: "TITLE_CHANGED",
  DESCRIPTION_UPDATED: "DESCRIPTION_UPDATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  ASSIGNEE_CHANGED: "ASSIGNEE_CHANGED",
  DUE_DATE_CHANGED: "DUE_DATE_CHANGED",
  SUBTASK_CREATED: "SUBTASK_CREATED",
  SUBTASK_REMOVED: "SUBTASK_REMOVED",
  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_EDITED: "COMMENT_EDITED",
  COMMENT_DELETED: "COMMENT_DELETED",
} as const;

export type TaskActivity = (typeof TaskActivity)[keyof typeof TaskActivity];
